version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend # mount
      - /frontend/node_modules # unmount node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # hot reload
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

  server:
    user: "root"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true